### ISSUE TITLE
Падает через некоторое время работы.

### ISSUE THREAD

**Issue by mobilesfinks** [alexrett/emplidler#7]
После падения выдало вот такой трейс
```
(emplidler:15320): libappindicator-WARNING **: 10:29:16.990: Unable to get the session bus: Could not connect: Connection refused

(emplidler:15320): LIBDBUSMENU-GLIB-WARNING **: 10:29:16.991: Unable to get session bus: Could not connect: Connection refused

(emplidler:15320): Gdk-CRITICAL **: 10:29:18.472: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Maximum number of clients reachedfatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x7f1a95226500]

runtime stack:
runtime.throw(0x732361, 0x2a)
        /usr/local/go/src/runtime/panic.go:1112 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:671 +0x46a

goroutine 8 [syscall]:
runtime.cgocall(0x690dd0, 0xc00015af38, 0x4014c500)
        /usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc00015af08 sp=0xc00015aed0 pc=0x40687b
github.com/alexrett/idler._Cfunc_XDefaultRootWindow(0x0, 0x0)
        _cgo_gotypes.go:84 +0x4a fp=0xc00015af38 sp=0xc00015af08 pc=0x52930a
github.com/alexrett/idler.(*Idle).getIdleTime.func1(0x0, 0x0)
        /home/malikov/go/pkg/mod/github.com/alexrett/idler@v0.0.0-20200313005634-cbdd0edc8241/idler_linux.go:13 +0x4d fp=0xc00015af68 sp=0xc00015af38 pc=0x52966d
github.com/alexrett/idler.(*Idle).getIdleTime(0xbb1310, 0x4e)
        /home/malikov/go/pkg/mod/github.com/alexrett/idler@v0.0.0-20200313005634-cbdd0edc8241/idler_linux.go:13 +0x5c fp=0xc00015afa8 sp=0xc00015af68 pc=0x5295bc
github.com/alexrett/idler.(*Idle).GetIdleTime(...)
        /home/malikov/go/pkg/mod/github.com/alexrett/idler@v0.0.0-20200313005634-cbdd0edc8241/idler.go:17
main.loopIdler()
        /home/malikov/test/emplidler/main.go:160 +0x92 fp=0xc00015afe0 sp=0xc00015afa8 pc=0x68fd82
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00015afe8 sp=0xc00015afe0 pc=0x465581
created by main.main
        /home/malikov/test/emplidler/main.go:63 +0x108

goroutine 1 [syscall, 31 minutes, locked to thread]:
github.com/getlantern/systray._Cfunc_nativeLoop(0xe92cd0, 0x20c00000400, 0x0)
        _cgo_gotypes.go:122 +0x4d
github.com/getlantern/systray.nativeLoop(0x725dd0, 0x9, 0x400, 0x20c)
        /home/malikov/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20200313211918-6a2da1056d32/systray_nonwindows.go:20 +0x55
github.com/getlantern/systray.RunWithAppWindow(0x725dd0, 0x9, 0x400, 0x20c, 0x73d7b0, 0x73d7a0)
        /home/malikov/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20200313211918-6a2da1056d32/systray.go:85 +0xa9
main.main()
        /home/malikov/test/emplidler/main.go:65 +0x14b

goroutine 73 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f1a56cc4f18, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0000c8098, 0x72, 0xe00, 0xe65, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000c8080, 0xc00024b000, 0xe65, 0xe65, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000c8080, 0xc00024b000, 0xe65, 0xe65, 0x203000, 0x52a53b, 0xc00010407e)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000284048, 0xc00024b000, 0xe65, 0xe65, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0004e2060, 0xc00024b000, 0xe65, 0xe65, 0x5f7dac, 0x0, 0xc000159918)
        /usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc000180958, 0x78ffa0, 0xc0004e2060, 0x40d575, 0x6d6020, 0x7146a0)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000180700, 0x7902a0, 0xc000284048, 0x5, 0xc000284048, 0xc00018e0c0)
        /usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000180700, 0x0, 0x0, 0xc00019ed20)
        /usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000180700, 0xc000104000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
net/http.(*persistConn).Read(0xc00008e480, 0xc000104000, 0x1000, 0x1000, 0xc000159eb0, 0x462b40, 0xc000159eb0)
        /usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc000061e00)
        /usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000061e00, 0x1, 0x2, 0x0, 0x0, 0xc00019ec00, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc00008e480)
        /usr/local/go/src/net/http/transport.go:1978 +0x1a8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1647 +0xc56

goroutine 9 [select, 31 minutes]:
main.onReady()
        /home/malikov/test/emplidler/main.go:121 +0x233
github.com/getlantern/systray.RunWithAppWindow.func2(0xc000028120, 0x73d7b0)
        /home/malikov/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20200313211918-6a2da1056d32/systray.go:71 +0x3e
created by github.com/getlantern/systray.RunWithAppWindow
        /home/malikov/go/pkg/mod/github.com/getlantern/systray@v0.0.0-20200313211918-6a2da1056d32/systray.go:69 +0x11b

goroutine 51 [select, 31 minutes]:
net/http.(*persistConn).writeLoop(0xc00008e900)
        /usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1648 +0xc7b

goroutine 50 [select, 31 minutes]:
net/http.(*persistConn).readLoop(0xc00008e900)
        /usr/local/go/src/net/http/transport.go:2099 +0x99e
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1647 +0xc56

goroutine 74 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc00008e480)
        /usr/local/go/src/net/http/transport.go:2277 +0x11c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1648 +0xc7b
```

**Comment by mobilesfinks** [comment]
в трейсе вижу `/home/malikov/test/` непонятно почему этот путь используется.

**Comment by alexrett** [comment]
https://github.com/alexrett/idler/issues/1 решено в этой вот ишью.
